[project]
name = "cdm"
version = "0.1.0"
description = "The ECLS CDM - an OMOP CDM expansion to map ECLS-related data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-glightbox>=0.4.0",
    "mkdocs-material>=9.6.14",
    "pre-commit>=4.2.0",
]
